import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  {
    // next-env.d.ts is auto-generated by Next.js and must not be edited;
    // next.config.ts isn't part of the TS project service (it's a Node-side
    // config file Next loads via its own loader).
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts', 'next.config.ts'],
  },
];
