import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  {
    // - next-env.d.ts is auto-generated by Next.js and must not be edited.
    // - next.config.ts / tailwind.config.ts / postcss.config.mjs are Node-side
    //   config files outside the TS project service.
    // - src/components/ui/** and src/hooks/use-toast.ts are vendored from
    //   shadcn — kept as-is so future `shadcn add` runs don't fight lint.
    // - e2e/** is run by Playwright's own ts loader; outside the Next
    //   tsconfig project service so the type-checked rules can't resolve it.
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'next.config.ts',
      'tailwind.config.ts',
      'postcss.config.mjs',
      'playwright.config.ts',
      'test-results/**',
      'playwright-report/**',
      'src/components/ui/**',
      'src/hooks/use-toast.ts',
      'e2e/**',
      // Sentry runtime config files at the workspace root — outside the Next
      // tsconfig project service (loaded directly by @sentry/nextjs's webpack
      // plugin and the instrumentation hook).
      'sentry.client.config.ts',
      'sentry.server.config.ts',
      'sentry.edge.config.ts',
    ],
  },
];
