import baseConfig from '../../eslint.config.mjs';

export default [
  ...baseConfig,
  {
    // - next-env.d.ts is auto-generated by Next.js and must not be edited.
    // - next.config.ts / tailwind.config.ts / postcss.config.mjs are Node-side
    //   config files outside the TS project service.
    // - src/components/ui/** and src/hooks/use-toast.ts are vendored from
    //   shadcn — kept as-is so future `shadcn add` runs don't fight lint.
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'next.config.ts',
      'tailwind.config.ts',
      'postcss.config.mjs',
      'playwright.config.ts',
      'test-results/**',
      'playwright-report/**',
      'src/components/ui/**',
      'src/hooks/use-toast.ts',
    ],
  },
];
