-- DO NOT REGENERATE THIS MIGRATION VIA `pnpm --filter @cpa/db generate`.
-- The block below `CREATE TABLE "event"` was hand-authored:
--   * 6 CHECK constraints (event_kind_valid, event_override_new_kind_valid,
--     event_override_invariants, event_hash_format, event_prev_hash_format,
--     event_idempotency_key_format)
--   * 1 CHECK on agent_call_cache (idempotency_key_format)
--   * RLS on event (ENABLE + FORCE + tenant-isolation policy)
--   * GRANTs for cpa_app on both tables
-- drizzle-kit will silently regenerate over these if you run `generate`
-- against this snapshot. If you need to change the table shape, write a
-- new migration (see 0007 for the pattern) — do NOT edit this file.

CREATE TABLE "agent_call_cache" (
	"idempotency_key" text PRIMARY KEY NOT NULL,
	"agent_name" text NOT NULL,
	"prompt_version" text NOT NULL,
	"output" jsonb NOT NULL,
	"tokens_in" integer NOT NULL,
	"tokens_out" integer NOT NULL,
	"model" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "event" (
	"id" uuid PRIMARY KEY NOT NULL,
	"tenant_id" uuid NOT NULL,
	"subject_tenant_id" uuid NOT NULL,
	"project_id" uuid,
	"milestone_id" uuid,
	"kind" text NOT NULL,
	"payload" jsonb NOT NULL,
	"classification" jsonb,
	"override_of_event_id" uuid,
	"override_new_kind" text,
	"override_reason" text,
	"prev_hash" text,
	"hash" text NOT NULL,
	"idempotency_key" text,
	"captured_at" timestamp with time zone NOT NULL,
	"captured_by_user_id" uuid NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "event_hash_unique" UNIQUE("hash")
);
--> statement-breakpoint
ALTER TABLE "event" ADD CONSTRAINT "event_tenant_id_tenant_id_fk" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event" ADD CONSTRAINT "event_subject_tenant_id_subject_tenant_id_fk" FOREIGN KEY ("subject_tenant_id") REFERENCES "public"."subject_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "event" ADD CONSTRAINT "event_captured_by_user_id_user_id_fk" FOREIGN KEY ("captured_by_user_id") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "event_feed_idx" ON "event" USING btree ("subject_tenant_id","captured_at" DESC NULLS LAST);--> statement-breakpoint
CREATE INDEX "event_kind_idx" ON "event" USING btree ("subject_tenant_id","kind");--> statement-breakpoint
CREATE INDEX "event_override_idx" ON "event" USING btree ("override_of_event_id");--> statement-breakpoint
CREATE UNIQUE INDEX "event_idempotency_unique" ON "event" USING btree ("idempotency_key") WHERE "event"."idempotency_key" IS NOT NULL;
--> statement-breakpoint
-- ============================================================
-- DB-level CHECK constraints (enforce invariants the type system can't)
-- ============================================================

-- Enum CHECK: kind must be one of the 13 known evidence kinds.
-- (drizzle's text-with-enum is a TS hint only — postgres won't reject
-- bad values without an explicit CHECK.)
ALTER TABLE "event" ADD CONSTRAINT event_kind_valid CHECK (
  kind IN (
    'HYPOTHESIS', 'DESIGN', 'EXPERIMENT', 'OBSERVATION', 'ITERATION',
    'NEW_KNOWLEDGE', 'UNCERTAINTY', 'TIME_LOG', 'ASSOCIATE_FLAG',
    'EXPENDITURE_NOTE', 'SUPPORTING', 'INELIGIBLE', 'OVERRIDE'
  )
);

-- override_new_kind, when set, must be one of the 12 classifiable kinds (NOT 'OVERRIDE').
ALTER TABLE "event" ADD CONSTRAINT event_override_new_kind_valid CHECK (
  override_new_kind IS NULL OR override_new_kind IN (
    'HYPOTHESIS', 'DESIGN', 'EXPERIMENT', 'OBSERVATION', 'ITERATION',
    'NEW_KNOWLEDGE', 'UNCERTAINTY', 'TIME_LOG', 'ASSOCIATE_FLAG',
    'EXPENDITURE_NOTE', 'SUPPORTING', 'INELIGIBLE'
  )
);

-- OVERRIDE invariants: kind='OVERRIDE' iff override_of_event_id + override_new_kind
-- + override_reason are all populated; non-OVERRIDE iff all three are null.
-- Either path enforces structural integrity that callers can't accidentally violate.
ALTER TABLE "event" ADD CONSTRAINT event_override_invariants CHECK (
  (kind = 'OVERRIDE'
    AND override_of_event_id IS NOT NULL
    AND override_new_kind IS NOT NULL
    AND override_reason IS NOT NULL)
  OR
  (kind <> 'OVERRIDE'
    AND override_of_event_id IS NULL
    AND override_new_kind IS NULL
    AND override_reason IS NULL)
);

-- Hash columns: hex-encoded SHA-256 are always exactly 64 lowercase hex chars.
-- prev_hash is nullable (first event in a chain); when set, same constraint applies.
ALTER TABLE "event" ADD CONSTRAINT event_hash_format CHECK (hash ~ '^[0-9a-f]{64}$');
ALTER TABLE "event" ADD CONSTRAINT event_prev_hash_format CHECK (
  prev_hash IS NULL OR prev_hash ~ '^[0-9a-f]{64}$'
);
ALTER TABLE "event" ADD CONSTRAINT event_idempotency_key_format CHECK (
  idempotency_key IS NULL OR idempotency_key ~ '^[0-9a-f]{64}$'
);

-- agent_call_cache idempotency_key is the PK and always populated; same format.
ALTER TABLE "agent_call_cache" ADD CONSTRAINT agent_call_cache_idempotency_key_format
  CHECK (idempotency_key ~ '^[0-9a-f]{64}$');

--> statement-breakpoint
-- ============================================================
-- RLS for event table — direct tenant_id (denormalised for index efficiency)
-- ============================================================

ALTER TABLE "event" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "event" FORCE ROW LEVEL SECURITY;

CREATE POLICY "event_tenant_isolation" ON "event"
  USING (tenant_id = current_setting('app.current_tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.current_tenant_id', true)::uuid);

-- agent_call_cache is intentionally NOT RLS-protected:
-- content-addressed by SHA-256(prompt_version || raw_text); identical inputs
-- across tenants legitimately share a cache entry. No tenant data leaks because
-- the only thing the key reveals is "someone classified text X" — which the
-- requester already knows.

GRANT SELECT, INSERT, UPDATE, DELETE ON "event" TO cpa_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON "agent_call_cache" TO cpa_app;